
services:
  frontend:
    image: flaviusfetean/docker-react-i:latest
    build:
      context: ./faq-front
      dockerfile: Dockerfile
    ports:
        - "3000:3000"
    networks:
        faq-assistant-network:
            ipv4_address: 172.16.200.10

  backend:
    image: flaviusfetean/backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ollama-container
    networks:
      faq-assistant-network:
        ipv4_address: 172.16.200.11

  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: faq_db
    ports:
      - "5432:5432"
    networks:
      faq-assistant-network:
        ipv4_address: 172.16.200.12

  ollama-container:
    image: flaviusfetean/ollama_orca:latest
    build:
      context: ./ollama
      dockerfile: Dockerfile
    ports:
        - "11434:11434"
    networks:
        faq-assistant-network:
            ipv4_address: 172.16.200.13

networks:
  faq-assistant-network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.200.0/24